services:
  rpi-monitoring:
    container_name: rpi-monitoring
    build: .
    restart: unless-stopped
    network_mode: host
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_PREFIX=${MQTT_PREFIX}
      - CPU_TEMPERATURE_ENABLED=${CPU_TEMPERATURE_ENABLED}
      - CPU_TEMPERATURE_INTERVAL=${CPU_TEMPERATURE_INTERVAL}
      - CPU_TEMPERATURE_UNIT=${CPU_TEMPERATURE_UNIT}
      - POWER_SUPPLY_ENABLED=${POWER_SUPPLY_ENABLED}
      - POWER_SUPPLY_INTERVAL=${POWER_SUPPLY_INTERVAL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
